services:
  flask-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5005:5000"
    volumes:
      - ./app:/app
    environment:
      FLASK_ENV: development
      FLASK_APP: app/main.py
      FLASK_RUN_PORT: 5005
      FLASK_DEBUG: 1
      FLASK_HOST: 0.0.0.0
    networks:
      - flask-network

networks:
  flask-network:
    driver: bridge
